### ISSUE TITLE
Can't access attributes such as path from the XFile

### ISSUE THREAD

**Issue by LeinHeart** [flutter-form-builder-ecosystem/form_builder_image_picker#37]
## Environment

**Package version:**  

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on Mac OS X 10.14.6 18G103 darwin-x64, locale en-ID)
    • Flutter version 3.0.5 at /Users/leinheart1688/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/leinheart1688/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Programming/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Programming/Xcode.app/Contents/Developer
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.10.0 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Programming/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Programming/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.14.6 18G103 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

<details>
  <summary>Code sample</summary>

```
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final _formKey = GlobalKey<FormBuilderState>();

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: FormBuilder(
        key: _formKey,
        child: Column(
          
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FormBuilderImagePicker(name: 'photo'),
            ElevatedButton(
               child: const Text('Submit'),
               onPressed: () async {
                  print(_formKey.currentState!.fields['photo']?.value);
                  XFile file = _formKey.currentState!.fields['photo']?.value;
                  print(file.path);
               }
          ],
        ),
      ),
    );
  }
}
```

</details>

## Description

**Expected behavior:**
Printing out the path of the images that has been chose from android phone gallery.
I need the path of the image so I can upload the image to my server.

**Current behavior:**
Printing out error 
```
I/flutter (30228): [Instance of 'XFile']
E/flutter (30228): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'XFile'
E/flutter (30228): #0      _CreateMaintenancePageState.build.<anonymous closure> (package:maintenance_flutter_3/views/create_maintenance_page.dart:417:37)
E/flutter (30228): #1      _CreateMaintenancePageState.build.<anonymous closure> (package:maintenance_flutter_3/views/create_maintenance_page.dart:386:40)
E/flutter (30228): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005:21)
E/flutter (30228): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
E/flutter (30228): #4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
E/flutter (30228): #5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
E/flutter (30228): #6      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269:7)
E/flutter (30228): #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (30228): #8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:449:20)
E/flutter (30228): #9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
E/flutter (30228): #10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
E/flutter (30228): #11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
E/flutter (30228): #12     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
E/flutter (30228): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
E/flutter (30228): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
E/flutter (30228): #15     _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (30228): #16     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (30228): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (30228): #18     _invoke1 (dart:ui/hooks.dart:170:10)
E/flutter (30228): #19     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
E/flutter (30228): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
```

## Steps to reproduce

1. Install the app directly to my Android Phone
2. Pick Image from gallery
3. Press Submit Button

**Comment by seiitbek** [comment]
have the same problem, will downgrade of the version solve the problem?

**Comment by deandreamatias** [comment]
I tested this code example. The behavior is expected.
If you see with detail, can see that this print `I/flutter (30228): [Instance of 'XFile']` Is a list of XFile so, if you need get one image, you need do some like this:

```dart
List<XFile> files = _formKey.currentState!.fields['photo']?.value;
print(file.first.path);
```

Please test and if work has expected, close this issue

**Comment by seiitbek** [comment]
Thank u very much, but in my case it works a bit different
it works when I use List<dynamic> at the beginning, not List<XFile>

**Comment by seiitbek** [comment]
Thank u very much, in my case it works a bit different
it works when I use `List<dynamic>` at the beginning, not `List<XFile>`

**Comment by LeinHeart** [comment]
> I tested this code example. The behavior is expected. If you see with detail, can see that this print `I/flutter (30228): [Instance of 'XFile']` Is a list of XFile so, if you need get one image, you need do some like this:
> 
> ```dart
> List<XFile> files = _formKey.currentState!.fields['photo']?.value;
> print(file.first.path);
> ```
> 
> Please test and if work has expected, close this issue

Hello! I've tested the code and it work returning the path to my image!
```
I/flutter ( 8803): [Instance of 'XFile']
I/flutter ( 8803): /data/user/0/com.example.maintenance_flutter_3/cache/image_picker5115871779577387959.jpg
```

Thank you very much for the quick reply!
